version: "3.8"

services:
    api:
        build: ./map
        ports:
            - 80:80
        environment:
            - DB_URL=mongodb://test_database/map
        volumes:
            - ./map:/map
    db:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - taskdb:/data/db
volumes:
    taskdb:
















